# Copyright 2020-2023 Open Networking Foundation (ONF) and the ONF Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: v2
description: A Helm chart to install a VOLTHA stack on existing infrastructure
keywords:
  - "onf"
  - "voltha"
  - "openolt-adapters"
  - "openonu-adapters"
home: "https://www.opennetworking.org/voltha"
icon: "https://guide.opencord.org/logos/voltha.svg"
maintainers:
  - name: "Open Networking Foundation"
    email: "info@opennetworking.org"
    url: "https://www.opennetworking.org"
name: voltha-stack
appVersion: "2.12"
version: 2.12.4
dependencies:
  - name: voltha
    repository: file://../voltha
    version: 2.12.10
    condition: voltha.enabled
  - name: voltha-adapter-openonu
    repository: file://../voltha-adapter-openonu
    version: 2.12.0
    condition: voltha-adapter-openonu.enabled
  - name: voltha-adapter-openolt
    repository: file://../voltha-adapter-openolt
    version: 2.12.5
    condition: voltha-adapter-openolt.enabled
  - name: voltha-go-controller
    repository: file://../voltha-go-controller
    version: 0.1.3
    condition: voltha-go-controller.enabled
