{{- if and .Values.global.redis.cluster.enabled .Values.global.redis.sentinel.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-{{ template "redis.fullname" . }}-node-0
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-data-{{ template "redis.fullname" . }}-node-0
    namespace: default
  hostPath:
    path: "{{ .Values.global.redis.volumePath }}/redis"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.global.hostname.worker1 }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-{{ template "redis.fullname" . }}-node-1
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-data-{{ template "redis.fullname" . }}-node-1
    namespace: default
  hostPath:
    path: "{{ .Values.global.redis.volumePath }}/redis"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.global.hostname.worker2 }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-{{ template "redis.fullname" . }}-node-2
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-data-{{ template "redis.fullname" . }}-node-2
    namespace: default
  hostPath:
    path: "{{ .Values.global.redis.volumePath }}/redis"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.global.hostname.worker3 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-{{ template "redis.fullname" . }}-node-0
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-{{ template "redis.fullname" . }}-node-1
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-{{ template "redis.fullname" . }}-node-2
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"

{{- else }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-{{ template "redis.fullname" . }}-0
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.volumePath }}/data/redis"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-{{ template "redis.fullname" . }}-0
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"


{{- end }}

